type: http
name: Get application details
url: '{{baseUrl}}/applications/:applicationId'
method: GET
headers:
  - key: Accept
    value: application/json
pathVariables:
  - key: applicationId
    value: string
examples:
  - response:
      statusCode: 200
      statusText: OK
      body:
        type: json
        content: |-
          {
            "id": "string",
            "applicantId": "string",
            "productType": "string",
            "requestedAmount": 7975.3488758018575,
            "termMonths": 8283,
            "status": "withdrawn",
            "createdAt": "1957-05-10T11:41:47.653Z",
            "updatedAt": "1960-12-27T14:23:16.112Z",
            "underwritingResult": {
              "applicationId": "string",
              "status": "completed",
              "decision": "denied",
              "riskScore": 2,
              "evaluatedAt": "2018-06-10T05:07:27.371Z"
            }
          }
      headers:
        - key: Content-Type
          value: application/json
    name: Application details
  - response:
      statusCode: 404
      statusText: Not Found
      body:
        type: json
        content: |-
          {
            "code": "string",
            "message": "string",
            "details": {}
          }
      headers:
        - key: Content-Type
          value: application/json
    name: Application not found
