type: http
name: List loan applications
url: '{{baseUrl}}/applications?status=submitted&productType=auto_loan&limit=25&offset=0'
method: GET
headers:
  - key: Accept
    value: application/json
queryParams:
  - key: status
    value: submitted
    description: Filter by application status
  - key: productType
    value: auto_loan
    description: Filter by loan product type
  - key: limit
    value: '25'
  - key: offset
    value: '0'
examples:
  - response:
      statusCode: 200
      statusText: OK
      body:
        type: json
        content: |-
          {
            "data": [
              {
                "id": "string",
                "applicantId": "string",
                "productType": "string",
                "requestedAmount": 2915.385248148947,
                "termMonths": 943,
                "status": "under_review",
                "createdAt": "1957-10-11T23:01:06.163Z",
                "updatedAt": "1965-06-16T21:34:41.044Z",
                "underwritingResult": {
                  "applicationId": "string",
                  "status": "failed",
                  "decision": "approved",
                  "riskScore": 97,
                  "evaluatedAt": "2004-07-09T06:52:51.573Z"
                }
              },
              {
                "id": "string",
                "applicantId": "string",
                "productType": "string",
                "requestedAmount": 4203.066591024016,
                "termMonths": 8357,
                "status": "under_review",
                "createdAt": "1978-09-05T08:44:34.030Z",
                "updatedAt": "2000-06-16T21:19:25.030Z",
                "underwritingResult": {
                  "applicationId": "string",
                  "status": "completed",
                  "decision": "denied",
                  "riskScore": 46,
                  "evaluatedAt": "2020-06-25T05:45:39.056Z"
                }
              }
            ],
            "total": 2364,
            "limit": 6137,
            "offset": 4283
          }
      headers:
        - key: Content-Type
          value: application/json
    name: List of applications
